### ISSUE TITLE
Property or method "isMobile" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by xiongzhiqing** [livelybone/vue-select#1]
![image](https://user-images.githubusercontent.com/13410719/53067329-b42a5c00-350e-11e9-9c30-2261d8bc298e.png)

**Comment by xiongzhiqing** [comment]
![image](https://user-images.githubusercontent.com/13410719/53067371-e1770a00-350e-11e9-8873-b937bd71c915.png)

**Comment by livelybone** [comment]
Thanks for your reminding, this bug has been fixed in the latest version(2.3.0)
