### ISSUE TITLE
Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by liyincode** [livelybone/vue-select#3]
你好，非常感谢提供插件让我们使用。但是在使用过程中，遇到点问题。

F12，会报一下错误
`index.js:428 Uncaught TypeError: Cannot read property 'contains' of undefined
    at VueComponent.toggle (index.js:428)
    at boundFn (vue.esm.js:188)`

经 Google 后，`contain` [方法已过时](https://stackoverflow.com/questions/19589465/why-javascript-contains-property-is-not-working-in-chrome-browser) 可替换成 ` indexOf`
https://github.com/livelybone/vue-select/blob/7a99e7b84f9ff13020bc61e6a48f9c73807d0fa1/src/common/Mixin.js#L94

版本：`2.5.0`
浏览器：Google Chrome`78.0.3904.97`

**Comment by livelybone** [comment]
你在你的代码中是如何使用的？方便放一部分源代码么？

**Comment by liyincode** [comment]
- main.js
```
 import { Cascader } from '@livelybone/vue-select';
 import '@livelybone/vue-select/lib/css/index.css';
 Vue.component('Cascader', Cascader);
```
- index.vue
```
<div v-show="isGroupSelectValid()"
        class="group-wrap">
        <Cascader
          class="cascader-top-search select"
          expandType="hover"
          changeOnSelect
          v-model="groupSelect"
          :scrollbarProps="{isMobile:isMobile, maxHeight: '28vh'}"
          :options="$store.getters.topGroupOption">
        </Cascader>
</div>
```

**Comment by livelybone** [comment]
你加 :popperProps="{}" 试试，我测出来是 popperProps 为空时代码运行错误

**Comment by livelybone** [comment]
或者尝试升级到 2.6.5

**Comment by superau** [comment]
非常感谢，通过添加 `:popperProps="{}"` 不再报错，正常运行。

很好奇，这个属性是做什么的

**Comment by liyincode** [comment]
非常感谢，通过你的方法，问题已经解决，正常运行！

**Comment by livelybone** [comment]
这个组件引用了 popperJs 库来帮助卡片定位，popperProps 用于定制它的一些配置。按理来讲 popperProps 可以不传，之前没有注意这个问题
现在已经在 2.6.5 对这个问题进行了修复
&nbsp;


刘志平 (livelybone)&nbsp;&nbsp;
中国 浙江 杭州 | UI设计师&前端工程师
信息技术和服务 | 北京大唐高鸿数据技术网络有限公司




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuaiyin"<notifications@github.com&gt;; 
发送时间: 2019年11月11日(星期一) 下午3:35
收件人: "livelybone/vue-select"<vue-select@noreply.github.com&gt;; 
抄送: "刘志平"<2631541504@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelybone/vue-select] Cannot read property &#39;contains&#39; of undefined (#3)




非常感谢，通过添加 :popperProps="{}" 不再报错，正常运行。
 
很好奇，这个属性是做什么的
