### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by greyfur** [livelybone/vue-select#5]
![bugimg](https://github.com/livelybone/vue-select/assets/29827552/7f258c08-e208-4f10-ad6e-f987c660e38a)
使用cascader组件，先选择一个三级的值[8,9,12],将can-edit先置为false再置为true,选择[8,10]或者[8,11]的时候，input事件返回的值如图，就会乱掉。

**Comment by livelybone** [comment]
Thanks..
I fixed it in version 2.7.0
